### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by soosp** [node-red-contrib/node-red-contrib-mikrotik#29]
**Is your feature request related to a problem? Please describe.**
If you want to access a MikroTik device on an unreliable network it is unsafe without SSL/TLS.

**Describe the solution you'd like**
Use api-ssl instead of api even if with self signed or custom CA signed certificates.

**Describe alternatives you've considered**
There are not any alternatives of encrypted connections on unreliable networks.

**Additional context**

**Comment by konne** [comment]
Hi @soosp 
thanks for your feature request.
The underlying library already supports ssl-api.

```json
tls: {
    rejectUnauthorized: false,
    ciphers: 'ADH-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384',
},
port: config.sslPort
```

I will try to add and test this in the next few days.

**Comment by konne** [comment]
@soosp I added the functionality in the new 0.6.0 release.
Please can you test this and give me feedback

**Comment by soosp** [comment]
Thank you for this awesome quick solution! It was tested with self signed certificate and certificate signed with my custom CA. The mikrotik node has worked well in both case.
