### ISSUE TITLE
consolidation of  package

### ISSUE THREAD

**Issue by konne** [node-red-contrib/node-red-contrib-mikrotik#5]
Hi, I really like to consolidate this package so that the node-red-contrib-mikrotik, node-red-contrib-mikrotik2, node-red-contrib-mikrotik3 finds and ends.
Are you willing to transfer / handover the npm and this repo to me?

bye Konrad

**Comment by konne** [comment]
@0nikola1 same question to you with your node-red-contrib-mikrotik3 fork

**Comment by konne** [comment]
@0nikola1 thx,
can you please give me also access to the npm package, so that I can upload new versions?
I have the same name on npm (konne)

**Comment by konne** [comment]
@bladerunner2020 what do you think?

**Comment by 0nikola1** [comment]
> 
> 
> @0nikola1 thx,
> can you please give me also access to the npm package, so that I can upload new versions?
> I have the same name on npm (konne)

I am using this myself and I created fork as when something breaks I want to be able to fix it and publish

**Comment by bladerunner2020** [comment]
@konne sorry for later replay - was busy this week. 
 I added you to collaborators. so you should have been able to make changes.

**Comment by konne** [comment]
@bladerunner2020 
Please can you transfer the package (Settings -> Transfer). In personal accounts, it is for example not possible to have access to secrets as a collaborator and I like to create a full CI / CD pipeline.

My second request would be, that you can give me access to the npm package. There you just have to add me in npmjs als a collaborator.

**Comment by konne** [comment]
> I am using this myself and I created fork as when something breaks I want to be able to fix it and publish. As long as I have access to publish if needed you are free to modify it.

@0nikola1 I fully understand your request and I would be happy if you can just work also on the main package. I will create a full CI/CD pipeline, so that I will be easy after a PR just to create a new release.
I also like to collect the feature requests from the history and to take care that some more features
and especially more documentation around using of functions with parameters,... will be added to the repo.

**Comment by bladerunner2020** [comment]
> @bladerunner2020
> Please can you transfer the package (Settings -> Transfer). In personal accounts, it is for example not possible to have access to secrets as a collaborator and I like to create a full CI / CD pipeline.
> You can do this only good in Organisations. This is the reason I added https://github.com/node-red-contrib as Org and it would be great if you can transfer it to this place.
> I will add you also there as a maintainer.
> 
> My second request would be, that you can give me access to the npm package. There you just have to add me in npmjs als a collaborator.

done )

**Comment by konne** [comment]
@bladerunner2020 
thx, but I still have no access to the **npm** package so I can not update this.
Please can you add konne in the npm package as maintaner.

**Comment by bladerunner2020** [comment]
> thx, but I still have no access to the **npm** package so I can not update this.
> Please can you add konne in the npm package as maintaner.

Hmm. It's strange. I tried once again. please check if now it's ok.

**Comment by 0nikola1** [comment]
> kage. I will create a full CI/CD pipeline, so that I will be easy after a PR just to create a new release.

I remember I had some issues when using some command but I figured it out, I will take some time and create more documentation for using RAW messages and add some example node-red flows.

**Comment by konne** [comment]
@bladerunner2020 thanks, now the npm access is working

**Comment by konne** [comment]
@0nikola1 yes I had the same issue with raw messages and I found out to put in an array.
Great if you can document / or we can do it together. I will close this issue and let us follow up on the docu in issue #12
I work at the moment hard on #11
