### ISSUE TITLE
/interface/ethernet/monitor

### ISSUE THREAD

**Issue by konne** [node-red-contrib/node-red-contrib-mikrotik#8]
@DedMsk We will follow up on the issue from here: alhafoudh/node-red-contrib-mikrotik2#5

How I can monitor interfaces?
/interface/ethernet/monitor\n1
and many other commands don't work
(

**Comment by 0nikola1** [comment]
@DedMsk Which type of monitoring do you need? For interface traffic info I use something like 

`[{"id":"34844337.ceefbc","type":"mikrotik","z":"f0d0173f.b4a34","device":"","name":"","action":"9","x":680,"y":2720,"wires":[["dd3c5317.fd344"]]},{"id":"630604f7.ccb25c","type":"inject","z":"f0d0173f.b4a34","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"command\":[\"/interface/monitor-traffic\",\"=interface=ether1internet\",\"=once=true\"]}","payloadType":"json","x":550,"y":2720,"wires":[["34844337.ceefbc"]]},{"id":"dd3c5317.fd344","type":"debug","z":"f0d0173f.b4a34","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":850,"y":2720,"wires":[]}]`
